@startuml
skinparam linetype ortho
skinparam classAttributeIconSize 0
abstract class Carte {
  +nom :String
}
abstract class CarteSpe {
  +desc :String
}
class Stop {
  --
  <<create>>Stop()
}
class Trois {
  --
  <<create>>Trois()
}
class SecondeChance {
  --
  <<create>>SecondeChance()
}
class CarteNumero {
  + val valeur : int
  --
  <<create>>CarteNumero(valeur)
}
abstract class CarteBonus {
 --
  + calculerBonus(Total :Int) :Int
}
class Main {
  - SecondeChance :CarteSecondeChance?
  - joueur : Joueur
  --
  <<create>>Main(Num, Bonus, SeceondeChance, Joueur)
  + calculerScore() : int
  + AjouteNum(carteN:CarteNumero)
  + AjoutBonus(carteB:CarteBonus)
  + setSecondeChance(carteS: SecondeChance)
  + possedeNum(V: int):Boolean
  + scorePartie():Int
  + scoreManche(): Int
  + vider()
}
class Paquet {
  --
  <<create>>Paquet()
  + piocher() :Carte
  + melanger()
  + estVide() :Boolean
  + taille() :Int
}
class Defausse {
  --
  <<create>>Defausse()
  + ajouter(carte : Carte)
  + vider() : List<Card>
}
class Joueur {
  - val nom : String
  - val scoreTotal :int
  - val estDanslaManche:Boolean
  - val Flip7 :Boolean
  - val main :Main
  --
  <<create>>Joueur(nom, scoreTotale, estDanslaManche, Flip7, Main)
  + sauter()
  + stopper()
}
class Manche {
  - val paquet :Paquet
  - val defausse :Defausse
  - val donneur :Joueur
  --
  <<create>> Manche(paquet, defausse, joueur, donneur)
  + demarrer()
  + distribuer(joueur :Joueur)
  + terminer()
}
class Partie {
    + val Joueur: List<Joueur>
    + val scoreObjectif: Int
    --
    <<create>>Partie(joueur, scoreObjectif, manchesCourantes)
    +Demarrer()
    +JouerManche()
    +EstTerminer():Boolean
    +DeterminerVainqueur():Joueur
}
class Plus{
   val points :Int
   --
   <<create>>Plus()
}
class Fois{
  --
  <<create>>Fois()
}
Manche "*"<--"1" Partie : MutableList<Manche>
Paquet "1"<--"1" Manche 
Paquet "1" <-- "1" Defausse : réapprovisionnement
Defausse "1"<--"1" Manche
Carte "0..94"<--"1" Defausse : MutableList<Carte>
Carte "0..94"<--"1" Paquet : ArrayDeck<Carte>
CarteSpe --|> Carte
CarteNumero --|> Carte
CarteBonus --|> Carte
Stop --|> CarteSpe
Trois --|> CarteSpe
SecondeChance --|> CarteSpe
Plus --|> CarteBonus
Fois --|> CarteBonus
CarteNumero "0..7"<--"1" Main : MutableList<CarteNumero>
SecondeChance "1"<--"1" Main
CarteBonus "6"<--"1" Main : MutableListe<CarteBonus>
CarteSpe "9"<--"1" Main : MutableList<CarteSpe>
Main "1"<--"1" Joueur
Joueur "2..4"<--"1..*" Manche : List<Joueur>
@enduml